CIRCUITPY_WIFI_SSID = "canspy"
CIRCUITPY_WIFI_PASSWORD = "canspycanspy"
CIRCUITPY_WEB_API_PASSWORD = "canspy"
CIRCUITPY_WEB_API_PORT = 80
MQTT_SUB = "/canspy/%/config"
MQTT_PUP= "/canspy/%/data"
MQTT_HOST = "canspy"
MQTT_USER = ""
MQTT_PASSWORD = ""

